### ISSUE TITLE
Create folder for `cart`

### ISSUE THREAD

**Issue by pablo-clueless** [CommunityPro/ecommerce-api#23]
- Create folder `cart` in `src/modules`.
- Create the files `cart.controller.ts`, `cart.dto.ts`, `cart.route.ts`, and `cart.service.ts` in the folder.

**Comment by damtrix** [comment]
i want to know what this entails,

**Comment by pablo-clueless** [comment]
This is a `module` for the `cart`. We want to expose a cart endpoint in our API where a user can perform CRUD operations to simulate how a normal cart would work in a real-world scenario. This module would follow the same pattern as the `product` and `category`, with controllers, dtos, routes, and services.

**Comment by damtrix** [comment]
Ok. I will like to work on this
