### ISSUE TITLE
Create middleware for file upload

### ISSUE THREAD

**Issue by pablo-clueless** [CommunityPro/ecommerce-api#24]
- Create a file `upload` in `common/middlewares`.
- Create a multer upload function middleware.

**Comment by Jummate** [comment]
Boss, you can assign this issue to me.

**Comment by Jummate** [comment]
Boss, where are the uploaded files going to be saved?. I mean, like a destination?. I want to point multer to this location.

**Comment by pablo-clueless** [comment]
We're saving in memory for multer. We're probably going to use Redis to hold the data for a little while, but go with memory for now.

**Comment by Jummate** [comment]
All right boss.
