### ISSUE TITLE
Create the schemas

### ISSUE THREAD

**Issue by pablo-clueless** [CommunityPro/ecommerce-api#4]
- Create the `category ` and `product` schemas in `schemas/category.ts ` and `schemas/product.ts` respectively and export in `schemas/index.ts`

**Comment by williamssam** [comment]
Boss, @pablo-clueless I want this 😮‍💨

**Comment by bnjox** [comment]
@williamssam  and @pablo-clueless 
Is anyone working on this currently??

**Comment by williamssam** [comment]
@sparrowsl  I think this is already implemented, we just need to close this issue

**Comment by pablo-clueless** [comment]
The schemas have been created.
